### ISSUE TITLE
Film and Television appear twice in Topic drop-down menu

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#651] opened 2016-11-11 15:54 UTC
Film and Television appears twice in the Topic drop-down menu on search results. One is correct and looks like "Film and Television" and the other has the I in film capitalized and looks like "FIlm and Television"

**Comment by jasoncorum** [comment] 2017-01-04 14:52
**Done When** 'Film and Television' appears correctly capitalized and only once in the topic dropdown.

**Comment by jasoncorum** [comment] 2017-01-04 20:34
@caseyedavis12 - This issue is caused by the metadata for the records available at the link below:
http://openvault.wgbh.org/catalog?f%5Baccess%5D%5B%5D=All+Records&f%5Btopics%5D%5B%5D=FIlm+and+Television

Once the topic is fixed in the records and they're re-ingested, the extra "FIlm and Television" should disappear.

**Comment by Muraszko** [comment] 2017-01-09 19:58
Metadata is fixed, just needs to be ingested on demo and production.
[Open_Vault_pbCore_201719145644_xml.zip](https://github.com/WGBH/openvault3/files/694502/Open_Vault_pbCore_201719145644_xml.zip)

**Comment by Muraszko** [comment] 2017-01-11 13:49
Jason and I re-ingested to both servers and resolved this issue.
![screen shot 2017-01-11 at 8 49 04 am](https://cloud.githubusercontent.com/assets/6650285/21850903/d53fa83e-d7da-11e6-89c9-661d124680b6.jpg)

**Closed by Muraszko** 2017-01-11 13:49 UTC
Labels: metadata
