### ISSUE TITLE
Ingest failure using ingest:run

### ISSUE THREAD

**Issue by Muraszko** [WGBH/openvault3#346] opened 2016-03-04 12:37 UTC
@mccalluc 
At first I thought it was an error because I was trying to ingest a single .xml file, but it gave me the same error trying to ingest a separate zip upload.
```
$  bundle exec cap demo ingest:run OV_PBCORE=/Users/michael_muraszko/Desktop/Open_Vault_pbCore_20163471353_QcpJ6gDKXw-V_38B4E344B4B34969A5BEA2ED170A1000.xml 
DEBUG [b63d1af4] Running /usr/bin/env if test ! -d /var/www/openvault/current; then echo "Directory does not exist '/var/www/openvault/current'" 1>&2; false; fi as ec2-user@54.163.95.179
DEBUG [b63d1af4] Command: if test ! -d /var/www/openvault/current; then echo "Directory does not exist '/var/www/openvault/current'" 1>&2; false; fi
DEBUG [b63d1af4] Finished in 0.264 seconds with exit status 0 (successful).
DEBUG [69c73bfc] Running /usr/bin/env [ -f /var/www/openvault/current/ingest_data/Open_Vault_pbCore_20163471353_QcpJ6gDKXw-V_38B4E344B4B34969A5BEA2ED170A1000.xml ] as ec2-user@54.163.95.179
DEBUG [69c73bfc] Command: [ -f /var/www/openvault/current/ingest_data/Open_Vault_pbCore_20163471353_QcpJ6gDKXw-V_38B4E344B4B34969A5BEA2ED170A1000.xml ]
DEBUG [69c73bfc] Finished in 0.059 seconds with exit status 1 (failed).
(Backtrace restricted to imported tasks)
cap aborted!
PBCore file not found. Upload pbcore with:

	OV_PBCORE=path/to/pbcore_file cap demo ingest:upload
```
Then I tried uploading with cap demo ingest:upload which put the file in current/ingest_data.

It didn't do anything, so then I re-ran cap demo ingest:run and it was successful.

Is ingest:run looking for the file in current/ingest_data?

This may not be a bug, but I had it in my notes from yesterday to use ingest:run.

**Comment by afred** [comment] 2016-03-04 15:20
@Muraszko correct, not a bug.

There are 3 relevant tasks:
  1. `cap demo ingest:upload OV_PBCORE=local_pbcore_file`
  2. `cap demo ingest:run OV_PBCORE=local_pbcore_file`
  3. `cap demo ingest:upload_and_run OV_PBCORE=local_pbcore_file`

I think the 2nd version is confusing, because you're specifying a local file, but it's a remote file that is getting ingested. There is a [ticket](https://github.com/WGBH/openvault3_deploy/issues/31) to fix this.

Also.. for deploy-related issues, please use the [issue tracker for `openvault3_deploy`](https://github.com/WGBH/openvault3_deploy/issues). Thanks!

**Comment by afred** [comment] 2016-03-04 15:22
closing as not a bug.

**Closed by afred** 2016-03-04 15:22 UTC
